### ISSUE TITLE
Make better output upon module import errors 

### ISSUE THREAD

**Issue by henriknorin** [looplab/skal#12]
Example output:
...lib/skal.py:209: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  if e.message.split(' ')[3] == name:
Warning: error in "meerkat.cli.worker", skipping
Traceback (most recent call last):
  File "...lib/skal.py", line 204, in _import_module
    module = __import__(name, fromlist=fromlist)
  File "...meerkast/cli/worker.py", line 12, in <module>
    from merkat.common.shotgun import ShotgunWrapper
ImportError: No module named merkat.common.shotgun
...lib/argparse.py:713: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  self.message = message
...lib/argparse.py:720: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return format % dict(message=self.message,
usage: meerkat [-h] [--version] {} ...
meerkat: error: invalid choice: 'import_edl' (choose from )

**Comment by maxekman** [comment]
Fixed in v0.1.12
